name: fastq-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nextflow=23.10.1
  - fastp=0.23.4
  - bwa=0.7.17
  - samtools=1.18
  - bcftools=1.18
  - picard=3.1.0
  - gatk4=4.4.0.0
  - qualimap=2.2.2d
  - multiqc=1.15
  - perl=5.32.1
  - openjdk=8.0.312
